#docker-compose.yml
version: '2'
  
  subgen:
    container_name: subgen
    image: mccloud/subgen
    environment:
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "UPDATEREPO=True"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "PLEXTOKEN=plextoken"
       - "PLEXSERVER=http://plexserver:32400"
       - "WEBHOOKPORT=8090"
    volumes:
       - "${TV}:/tv"
       - "${MOVIES}:/movies"
    ports:
       - "8090:8090"
