#docker-compose.yml
version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "PLEXTOKEN=plextoken"
       - "PLEXSERVER=http://plexserver:32400"
       - "JELLYFINTOKEN=token here"
       - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=8090"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=False"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "TRANSCRIBE_DEVICE=cpu"
       - "MODEL_PATH=."
    volumes:
       - "${TV}:/tv"
       - "${MOVIES}:/movies"
    ports:
       - "8090:8090"
