name: Build_Subgen_Dockerfile_CPU

on:
  push:
    paths:
      - 'requirements.txt'
      - 'Dockerfile.cpu'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from subgen.py
        id: get_version
        run: |
          version=$(grep -oP "subgen_version\s*=\s*'\K[^']+" subgen.py)
          echo "version=$version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.cpu
          push: true
          tags: |
            mccloud/subgen:cpu
            mccloud/subgen:${{ env.version }}-cpu
