name: Build_Subgen_Dockerfile_GPU

on:
  #push:
  #  branches:
  #    - 'main'
  #  paths-ignore:
  #    - '**.md'
  #    - '**.yml'
  workflow_dispatch:

jobs:
 
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add subgen/subgen.py
          git commit -m "Automated update subgen.py with version"
          git push
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GPU
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mccloud/subgen:latest
