name: ci

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mccloud/subgen:latest, mccloud/subgen:cpu
      -
        name: Build and push cuda
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.cuda
          push: true
          tags: mccloud/subgen:cuda, mccloud/subgen:gpu
       
